#!/usr/bin/env bash
#load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo chmod 666 /etc/haproxy/haproxy.cfg
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend backend-servers

backend backend-servers
    balance roundrobin
    server 190593-web-01 100.26.229.143:80 check
    server 190593-web-02 54.237.104.144:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restarti
